### PR TITLE
Response Warpper pattern and 409 for Register.

### PR DESCRIPTION
**Pull request by Howllo**
Using a response wrapper pattern to ease the process of communication between the service, controller, and front-end. Added a requested feature for the better response feedback to the user.

### CODE REVIEW

**Review by eggrain — COMMENTED** [review]
I like the Register Controller only invoking the one method service here compared to before, I'm not sure a `ApiResponse<T>` type is needed. Rather than the controller returning type `ResponseEntity<String>`, you can have it return `ResponseEntity<User>`, which includes a status code. To me the `ApiResponse<T>` is too similar to the `ResponseEntity<T>` type that it indicates a bad separation of responsibility between the layers. Preferably the controller would be the determiner of what status code is sent back too as that's generally expected of a controller to do. I would go for the service just returning the entity and throwing exceptions for the controller to handle personally, but if you disagreed with that approach as exceptions do add a lot of complexity, you probably do need a tuple return value or wrapper like you have for the entity and message about what happened

**Review by eggrain — APPROVED** [review]
Still would prefer the controller not orchestrate the registration with calling multiple register service methods, but it can be refactored later

**Comment by Howllo** [comment]
There’s nothing wrong with the design as it stands. The approach I’ve used aligns with best practices, and what you're suggesting—using exceptions as a logic gate—would lead to an anti-pattern. This would cause the program to be unnecessarily complicate the design without offering any real benefit.

Using the service calls like this allows for ease of flow for the determining the appropriate status code. This is correct and standard way to handle this scenario.

**Comment by Howllo** [comment]
There’s nothing wrong with the design as it stands. The approach I’ve used aligns with best practices, and what you're suggesting using exceptions as a logic gate would lead to an anti-pattern. This would cause the program to be unnecessarily complicate the design without offering any real benefit.

Using the service calls like this allows for ease of flow for the determining the appropriate status code. This is correct and standard way to handle this scenario.

**Pull request merged**
